version: "3.7"

services:
  webclient:
    container_name: webclient
    build:
      context: ./Client/booking-ally
      dockerfile: ./production/Dockerfile
    ports:
      - 80:80
    depends_on:
      - authservice
      - venueservice


  authservice:
    container_name: auth-service
    build: ./Backend/services/authentication

  venueservice:
    container_name: venue-service
    build: ./Backend/services/venue



