version: "3.7"

services:
  nginx:
    container_name: proxy
    build: ./Proxy/dev
    ports:
      - "80:80"
    depends_on:
      - authservice
      - venueservice
      - webclient

  webclient:
    container_name: webclient
    build:
      context: ./Client/booking-ally
      dockerfile: ./production/Dockerfile

  authservice:
    container_name: auth-service
    build: ./Backend/services/authentication
    environment:
      MONGODB_URI:
      JWT_SECRET:
      BUCKET_NAME:
      ACCESS_KEY:
      SECRET_ACCESS_KEY:

  venueservice:
    container_name: venue-service
    build: ./Backend/services/venue
    environment:
      MONGODB_URI:
      JWT_SECRET:



