version: "3.7"

services:
  webclient:
    container_name: webclient
    image: nicholasmurray/booking_ally_client
    ports:
      - 80:80
    depends_on:
      - authservice
      - venueservice

  authservice:
    container_name: auth-service
    image: nicholasmurray/authentication-service

  venueservice:
    container_name: venue-service
    image: nicholasmurray/venue-service



