version: "3.7"
# Development compose file, for use during development of the Web client to allow hot
# reload of the react site on port 80 without the container
services:
  nginx:
    container_name: proxy-service
    build: Proxy/dev
    ports:
      - "1405:80"
    depends_on:
      - authservice
      - venueservice
      - imageservice

  authservice:
    container_name: auth-service
    build: Backend/services/authentication
    environment:
      MONGODB_URI:
      JWT_SECRET:

  venueservice:
    container_name: venue-service
    build: Backend/services/venue
    environment:
      MONGODB_URI:
      JWT_SECRET:

  imageservice:
    container_name: image-service
    build: Backend/services/images
    environment:
      MONGODB_URI:
      JWT_SECRET:
      BUCKET_NAME:
      ACCESS_KEY:
      SECRET_ACCESS_KEY:



