version: "3.7"
# Deployment compose file used to build and deploy the docker containers in the
# current docker context.
# To deploy system open a terminal in the project directory and run "docker-compose up"
services:
  nginx:
    container_name: proxy-service
    build: ./Proxy/dev
    ports:
      - "80:80"
    depends_on:
      - authservice
      - venueservice
      - webclient
      - imageservice

  webclient:
    container_name: webclient
    build:
      context: ./Client/booking-ally
      dockerfile: ./production/Dockerfile

  authservice:
    container_name: auth-service
    build: ./Backend/services/authentication
    environment:
      MONGODB_URI:
      JWT_SECRET:
      BUCKET_NAME:
      ACCESS_KEY:
      SECRET_ACCESS_KEY:

  venueservice:
    container_name: venue-service
    build: ./Backend/services/venue
    environment:
      MONGODB_URI:
      JWT_SECRET:

  imageservice:
    container_name: image-service
    build: Backend/services/images
    environment:
      MONGODB_URI:
      JWT_SECRET:
      BUCKET_NAME:
      ACCESS_KEY:
      SECRET_ACCESS_KEY:


