version: "3.7"
# Deployment compose file used to deploy docker containers to the aws elastic
# container service. Docker needs to be in the aws context for this to work.
services:
  nginx:
    container_name: proxy
    image: nicholasmurray/proxy-service
    ports:
      - 80:80
    depends_on:
      - webclient
      - authservice
      - venueservice

  webclient:
    container_name: webclient
    image: nicholasmurray/booking_ally_client

  authservice:
    container_name: auth-service
    image: nicholasmurray/authentication-service
    environment:
      MONGODB_URI:
      JWT_SECRET:
      BUCKET_NAME:
      ACCESS_KEY:
      SECRET_ACCESS_KEY:

  venueservice:
    container_name: venue-service
    image: nicholasmurray/venue-service
    environment:
      MONGODB_URI:
      JWT_SECRET:



