# build environment
FROM node:13.12.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY Client/booking-ally/package.json ./
COPY Client/booking-ally/package-lock.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g --silent
COPY Client/booking-ally ./
CMD ["npm", "build"]

# production environment
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
