name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: nicholasmurray/booking_ally_client

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          if [ -f Web\ Client/booking-ally/Dockerfile.prod ]; then
            docker build --file Web\ Client/booking-ally/Dockerfile.prod --tag $IMAGE_NAME .
          else
            docker build --file Web\ Client/booking-ally/Dockerfile --tag $IMAGE_NAME .
          fi

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run:  docker login -u ${{ secrets.JIB_USER}} -p ${{ secrets.JIB_PASS}}

      - name: Push image to GitHub Container Registry
        run: |
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:
